name: Test Develop Branch

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Run Basic Tests for Develop
      # Ejecuta solo el test básico de la rama develop
      run: mvn -B test -Dtest=DevelopBasicTest --file ilerntale/pom.xml
